### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by Gitcrafter** [RuochenFu21/CreateAppliedKinetics#1]
it says, it requires minecraft 1.18.2, despite being a 1.19.2 mod

![2023-05-30_13 30 50](https://github.com/RuochenFu21/CreateAppliedKinetics/assets/81863925/d53be98a-b4e3-45af-829d-d0c4e3179653)

**Comment by Gitcrafter** [comment]
do you plan to make a 1.19.2 version?

**Comment by RuochenFu21** [comment]
When have time, maybe just today, not sure
