### ISSUE TITLE
[Design flaws] Simply and crudely disabling the embosser makes it impossible to create chips added by other modules

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [RuochenFu21/CreateAppliedKinetics#8]
BIRD OF PARADISE

https://www.curseforge.com/minecraft/mc-mods/applied-flux

**Comment by furuochen-dev** [comment]
Ok.

**Comment by furuochen-dev** [comment]
Semi-Fixed by allowing reënabling inscriber recipes in v1.4

**Comment by furuochen-dev** [comment]
An improvement to current system that allows this would be to automatically translate inscriber to create mod sequenced assembly recipe which would be a new feature, therefore I would add a enhancement tag
